packages:
  - apps/*
  - packages/*
  - tools/*
catalog:
  '@eslint/js': ^9.31.0
  '@hono/node-server': ^1.15.0
  '@hono/trpc-server': ^0.4.0
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-toast': ^1.2.14
  '@radix-ui/react-tooltip': ^1.2.7
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/react-form': ^1.14.1
  '@tanstack/react-query': ^5.83.0
  '@tanstack/react-router': ^1.127.3
  '@tanstack/router-devtools': ^1.127.3
  '@tanstack/router-plugin': ^1.127.5
  '@trpc/client': ^11.4.3
  '@trpc/server': ^11.4.3
  '@trpc/tanstack-react-query': ^11.4.3
  '@types/eslint-config-prettier': ^6.11.3
  '@types/node': ^24.0.13
  '@types/pg': ^8.15.4
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react-swc': ^3.10.2
  better-auth: ^1.2.12
  class-variance-authority: ^0.7.1
  dotenv-cli: ^8.0.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.2
  drizzle-valibot: ^0.4.2
  eslint: ^9.31.0
  eslint-config-prettier: ^10.1.5
  eslint-config-turbo: ^2.5.4
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.4
  globals: ^16.3.0
  hono: ^4.8.4
  next-themes: ^0.4.6
  pg: ^8.16.3
  prettier: ^3.6.2
  radix-ui: ^1.4.2
  react: ^19.1.0
  react-dom: ^19.1.0
  shx: ^0.4.0
  sonner: ^2.0.6
  superjson: ^2.2.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tailwindcss-animate: ^1.0.7
  tsup: ^8.5.0
  tsx: ^4.20.3
  turbo: ^2.5.4
  typescript: ^5.8.3
  typescript-eslint: ^8.36.0
  url-join: ^5.0.0
  valibot: ^1.1.0
  vite: ^7.0.4
ignoredBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: '>=0.25.0'
